### ISSUE TITLE
problème avec render

### ISSUE THREAD

**Issue by Baiiken** [4wip/Crowbot-Setup#13]
lorsque je lance le script sur render,le bot se lance mais ne répond pas (contrairement à lorsque je le lance avec mon pc)

**Comment by atomiciscool** [comment]
> lorsque je lance le script sur render,le bot se lance mais ne répond pas (contrairement à lorsque je le lance avec mon pc)

ta reussie a le fix?

**Comment by Baiiken** [comment]
non

**Comment by 4wip** [comment]
Le bot est en ligne?

**Comment by Baiiken** [comment]
> Le bot est en ligne?

oui il est en ligne depuis que j'aie lancé le service web ça aucun problème mais il ne répond pas (à part si je le lance depuis ma propre machine)

**Comment by 4wip** [comment]
> > Le bot est en ligne?
> 
> oui il est en ligne depuis que j'aie lancé le service web ça aucun problème mais il ne répond pas (à part si je le lance depuis ma propre machine)
> 

Essaye de vérifier si dans la config ta bien tout mis correctement exemple les ID. 
Activer les 3 intents du bot

**Comment by Baiiken** [comment]
> > > Le bot est en ligne?
> > 
> > 
> > oui il est en ligne depuis que j'aie lancé le service web ça aucun problème mais il ne répond pas (à part si je le lance depuis ma propre machine)
> 
> Essaye de vérifier si dans la config ta bien mis correctement ton ID. Activer les 3 intents du bot

J’ai déjà bien mis mon id et les 3 intents

**Comment by 4wip** [comment]
> > > > Le bot est en ligne?
> > > 
> > > 
> > > oui il est en ligne depuis que j'aie lancé le service web ça aucun problème mais il ne répond pas (à part si je le lance depuis ma propre machine)
> > 
> > Essaye de vérifier si dans la config ta bien mis correctement ton ID. Activer les 3 intents du bot
> 
> J’ai déjà bien mis mon id et les 3 intents 

Je peux rien faire de plus. Essaye de vérifier les instructions

**Comment by Baiiken** [comment]
> > > > > Le bot est en ligne?
> > > > 
> > > > 
> > > > oui il est en ligne depuis que j'aie lancé le service web ça aucun problème mais il ne répond pas (à part si je le lance depuis ma propre machine)
> > > 
> > > 
> > > Essaye de vérifier si dans la config ta bien mis correctement ton ID. Activer les 3 intents du bot
> > 
> > 
> > J’ai déjà bien mis mon id et les 3 intents
> 
> Ah c'est bon je vois ton problème avec render Vérifie le lien que ta mis au début est celui de ton fork GitHub J'ai vu sur le tien que dans la config. JSON tu n'a pas changer le ID par le tien c'est ça le problème. (Ignore les majs je suis sûr téléphone)

Dans le config je dois modifier l’id de l’owner sur le fork que j’aie fait c’est ça ?

**Comment by 4wip** [comment]
Exactement

**Comment by Baiiken** [comment]
je teste ça de suite merci

**Comment by Baiiken** [comment]
ça marche tjrs pas mdrrr

**Comment by Baiiken** [comment]
j'ai créé un nouveau web service au cas où, j'ai bien deploy le dernier commit, j'ai créé un nouveau cronjob, mais ça marche pas

**Comment by Baiiken** [comment]
non ras c'est bon ça marche juste comme un con j'avais pas changé le prefix dans le config

**Comment by Baiiken** [comment]
merci pour l'aide en tout cas

**Comment by 4wip** [comment]
Oublie de config

Si vous avez besoin d'une aide rapide allez sur le discord: https://dsc.gg/4wip
